[package]
name = "pt"
version = "0.1.0"
authors = ["mark"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.32", features = ["bundled", "static-link"] }
# sdl2 = { version = "0.32", features = ["bundled", "gfx", "static-link"] }
